use_frameworks!

platform :ios, '10.0'

target 'MFTAIdentity_Example' do
  pod 'MFTAIdentity', :path => '../'
  pod 'Alamofire', '~> 5.4'
  pod 'ObjectMapper', '~> 4.2'
  pod 'SVProgressHUD'

  target 'MFTAIdentity_Tests' do
    inherit! :search_paths

    
  end
end
